---
- debug: msg="running pre_hook():" 

- name: Set Grub Big Pages
  set_fact:
    grub_huge_pages: 'default_hugepagesz=1GB hugepagesz=1G hugepages=300'

- name: sethostname
  shell: hostnamectl set-hostname --static --transient `hostname`
  args:
    executable: /bin/bash
  register: sethostname
- debug:
    msg: Set sethostname {{ sethostname }}  


- name: setCPUAffinity
  shell: echo "CPUAffinity=0 18 36 54" | sudo tee --append /etc/systemd/system.conf
  args:
    executable: /bin/bash
  register: setCPUAffinity
- debug:
    msg: Set setCPUAffinity {{ setCPUAffinity }}  


- name: setIsolatedCores
  shell: echo "isolated_cores=1-17,19-35,37-53,55-71" | sudo tee --append /etc/tuned/cpu-partitioning-variables.conf
  args:
    executable: /bin/bash
  register: setIsolatedCores
- debug:
    msg: Set Islotaed Cores Result {{ setIsolatedCores }}  

- name: executeTuned-adm
  shell: tuned-adm profile cpu-partitioning
  args:
    executable: /bin/bash
  register: executeTuned-adm
- debug:
    msg: Set executeTuned-adm Result {{ executeTuned-adm }}  

- name: create Platform9 service group (pf9group)
  group:
    name: pf9group
    gid: "{{pf9_gid}}"
    state: present
  when: pf9_gid is defined
- name: create Platform9 service account (pf9)
  user:
    name: pf9
    shell: /bin/bash
    uid: "{{pf9_uid}}"
    home: /opt/pf9/home
    create_home: True
    groups: pf9group
    when: pf9_uid is defined
  when: pf9_account_status is defined and pf9_account_status.stdout.strip() == "not-exist"
- name: Create /opt/pf9/etc/nova/conf.d
  file:
    path: /opt/pf9/etc/nova/conf.d
    state: directory
    recurse: yes
    owner: pf9
    group: pf9grouop
  register: confd_dir

- name: setIsolatedCores
  shell: crudini --set /opt/pf9/etc/nova/conf.d/nova_override.conf DEFAULT vcpu_pin_set 1-17,19-35,37-53,55-71 
  args:
    executable: /bin/bash
- name: Check GRUB defaults and enable Hugepages if necessary
  lineinfile:
    path: /etc/default/grub
    backrefs: true
    regexp: '^GRUB_CMDLINE_LINUX="((?!.*{{ grub_huge_pages }}).*)"$'
    line: 'GRUB_CMDLINE_LINUX="\1 {{ grub_huge_pages }}"'
    backup: yes
  register: grubHugePages
- debug:
    msg: Grub Huge Pages Result {{ grubHugePages }}

- name: openstackCLI
  shell: |
    source /usr/bin/virtualenvwrapper.sh
    export WORKON_HOME=$HOME/.virtenvs
    mkvirtualenv os_cli
    pip install --upgrade --requirement https://raw.githubusercontent.com/platform9/support-locker/master/openstack-clients/requirements.txt --constraint https://raw.githubusercontent.com/openstack/requirements/stable/pike/upper-constraints.txt
    exit 0 
  args:
    executable: /bin/bash
  register: openstackCLI
- debug:
    msg: Set openstackCLI Result {{ openstackCLI }}  
